// swift-tools-version: 6.2

import PackageDescription

// The module graph mirrors beam-android's, and for the same reason: `BeamFFI`
// is the only target that links the XCFramework or names a generated type, so
// every target above it can be tested with no native library present. That is
// what lets the Apple suite run the way the Android one does -- see ADR-0013.
//
// Features are separate targets rather than folders in one, so the rule that a
// feature never imports another feature is enforced by the compiler instead of
// by convention. Cross-feature navigation is a closure the shell passes down.
//
// Everything below is built with explicit types, `var` and loops rather than
// array literals, `+` and `map`. That is not a style preference. Two rounds of
// CI failed here with "the compiler is unable to type-check this expression in
// reasonable time" -- first on a literal array of ten helper calls, then on
// `features.map { .byName(name: $0.name) }` even with both sides annotated.
// `Target.Dependency` conforms to several `ExpressibleBy` protocols and
// `.byName` is one of many overloads, so each element costs the solver real
// work, and the budget it gets varies by toolchain: this manifest resolved on
// Xcode 26.6 and gave up on 26.0.1. A loop has nothing to infer, which takes
// the question off the table instead of trading one expensive expression for a
// slightly cheaper one.

// MARK: - Shared dependency lists

let coreDependencies: [Target.Dependency] = [
    Target.Dependency.byName(name: "BeamCore"),
    Target.Dependency.byName(name: "BeamModel"),
]

var uiDependencies: [Target.Dependency] = coreDependencies
uiDependencies.append(Target.Dependency.byName(name: "BeamDesignSystem"))
uiDependencies.append(Target.Dependency.byName(name: "BeamUI"))

// MARK: - Features

let featureNames: [String] = [
    "BeamAuth",
    "BeamHome",
    "BeamLibraries",
    "BeamExplore",
    "BeamDetail",
    "BeamPlayer",
    "BeamDownloads",
    "BeamHistory",
    "BeamSettings",
    "BeamAdmin",
]

/// Features that drive playback, and so also need `BeamPlayback`.
let playbackFeatures: Set<String> = ["BeamPlayer", "BeamDownloads"]

var featureTargets: [Target] = []
var featureDependencies: [Target.Dependency] = []

for name in featureNames {
    var dependencies: [Target.Dependency] = uiDependencies
    if playbackFeatures.contains(name) {
        dependencies.append(Target.Dependency.byName(name: "BeamPlayback"))
    }
    let target: Target = .target(
        name: name,
        dependencies: dependencies,
        path: "Sources/Features/\(name)"
    )
    featureTargets.append(target)
    featureDependencies.append(Target.Dependency.byName(name: name))
}

// MARK: - Composite dependency lists

var uiTargetDependencies: [Target.Dependency] = coreDependencies
uiTargetDependencies.append(Target.Dependency.byName(name: "BeamDesignSystem"))

var playbackDependencies: [Target.Dependency] = coreDependencies
playbackDependencies.append(Target.Dependency.byName(name: "BeamFFI"))

var testingDependencies: [Target.Dependency] = coreDependencies
testingDependencies.append(Target.Dependency.byName(name: "BeamPlayback"))

var shellDependencies: [Target.Dependency] = uiDependencies
shellDependencies.append(Target.Dependency.byName(name: "BeamPlayback"))
shellDependencies.append(contentsOf: featureDependencies)

var unitTestDependencies: [Target.Dependency] = [
    Target.Dependency.byName(name: "BeamAppShell"),
    Target.Dependency.byName(name: "BeamTesting"),
]
unitTestDependencies.append(contentsOf: featureDependencies)

var snapshotTestDependencies: [Target.Dependency] = unitTestDependencies
snapshotTestDependencies.append(
    Target.Dependency.product(name: "SnapshotTesting", package: "swift-snapshot-testing")
)

// MARK: - Targets

var allTargets: [Target] = []

// Generated by `mise run core:apple`; gitignored.
allTargets.append(
    .binaryTarget(
        name: "BeamClientCoreFFI",
        path: "Frameworks/BeamClientCoreFFI.xcframework"
    )
)

// The UniFFI output, alone in its own target so it can be built in Swift 5
// language mode. UniFFI 0.32's async scaffolding does not satisfy Swift 6's
// `sending` closure rules, and this is generated code -- editing it would be
// undone by the next `core:bindgen:swift`, and relaxing the mode package-wide
// would give up strict concurrency on every line we actually wrote.
allTargets.append(
    .target(
        name: "BeamCoreBindings",
        dependencies: [Target.Dependency.byName(name: "BeamClientCoreFFI")],
        path: "Sources/BeamCoreBindings",
        swiftSettings: [.swiftLanguageMode(.v5)]
    )
)

allTargets.append(
    .target(
        name: "BeamFFI",
        dependencies: [Target.Dependency.byName(name: "BeamCoreBindings")],
        path: "Sources/BeamFFI"
    )
)

allTargets.append(.target(name: "BeamModel", path: "Sources/BeamModel"))

allTargets.append(
    .target(
        name: "BeamCore",
        dependencies: [
            Target.Dependency.byName(name: "BeamFFI"),
            Target.Dependency.byName(name: "BeamModel"),
        ],
        path: "Sources/BeamCore"
    )
)

allTargets.append(.target(name: "BeamDesignSystem", path: "Sources/BeamDesignSystem"))

allTargets.append(
    .target(
        name: "BeamUI",
        dependencies: uiTargetDependencies,
        path: "Sources/BeamUI"
    )
)

allTargets.append(
    .target(
        name: "BeamPlayback",
        dependencies: playbackDependencies,
        path: "Sources/BeamPlayback"
    )
)

allTargets.append(
    .target(
        name: "BeamTesting",
        dependencies: testingDependencies,
        path: "Sources/BeamTesting"
    )
)

allTargets.append(
    .target(
        name: "BeamAppShell",
        dependencies: shellDependencies,
        path: "Sources/BeamAppShell"
    )
)

allTargets.append(
    .testTarget(
        name: "BeamKitTests",
        dependencies: unitTestDependencies,
        path: "Tests/BeamKitTests"
    )
)

// Its own target so `apple:test` and `apple:snapshot` can select it: the
// reference images are only meaningful on the one simulator they were recorded
// on, so they must not run on every destination.
allTargets.append(
    .testTarget(
        name: "SnapshotTests",
        dependencies: snapshotTestDependencies,
        path: "Tests/SnapshotTests",
        exclude: ["__Snapshots__"]
    )
)

allTargets.append(contentsOf: featureTargets)

// MARK: - Package

let package = Package(
    name: "BeamKit",
    // Liquid Glass is the design language, not a progressive enhancement, so
    // the deployment target is the first OS that has it. Supporting one
    // release earlier would mean an `if #available` in every container view
    // and two visual languages to keep in step. See ADR-0013.
    platforms: [.iOS(.v26), .macOS(.v26)],
    products: [
        .library(name: "BeamAppShell", targets: ["BeamAppShell"])
    ],
    dependencies: [
        // Pinned exactly, not `from:`. The references this drives are pixel
        // comparisons, and the Xcode project resolves its own dependency graph
        // whose Package.resolved lives inside the generated (and gitignored)
        // .xcodeproj -- so a floating minor could change the renderer under CI
        // with nothing in the diff to explain the failure.
        .package(
            url: "https://github.com/pointfreeco/swift-snapshot-testing",
            exact: "1.19.4"
        )
    ],
    targets: allTargets
)
