// swift-tools-version: 6.2

import PackageDescription

// The module graph mirrors beam-android's, and for the same reason: `BeamFFI`
// is the only target that links the XCFramework or names a generated type, so
// every target above it can be tested with no native library present. That is
// what lets the Apple suite run the way the Android one does -- see ADR-0013.
//
// Features are separate targets rather than folders in one, so the rule that a
// feature never imports another feature is enforced by the compiler instead of
// by convention. Cross-feature navigation is a closure the shell passes down.

let coreDependencies: [Target.Dependency] = ["BeamCore", "BeamModel"]
let uiDependencies: [Target.Dependency] = coreDependencies + ["BeamDesignSystem", "BeamUI"]

/// Every feature depends on the same four targets and on nothing else.
func feature(_ name: String, extra: [Target.Dependency] = []) -> Target {
    .target(
        name: name,
        dependencies: uiDependencies + extra,
        path: "Sources/Features/\(name)"
    )
}

// Explicitly typed, and the dependency list computed once below. Without the
// annotations the type-checker has to infer `[Target]` from ten calls whose
// argument types are themselves inferred, and it gives up: CI failed with
// "the compiler is unable to type-check this expression in reasonable time"
// while the same manifest resolved locally on a newer toolchain.
let features: [Target] = [
    feature("BeamAuth"),
    feature("BeamHome"),
    feature("BeamLibraries"),
    feature("BeamExplore"),
    feature("BeamDetail"),
    feature("BeamPlayer", extra: ["BeamPlayback"]),
    feature("BeamDownloads", extra: ["BeamPlayback"]),
    feature("BeamHistory"),
    feature("BeamSettings"),
    feature("BeamAdmin"),
]

/// Every feature target, as a dependency list.
let featureDependencies: [Target.Dependency] = features.map { .byName(name: $0.name) }

let package = Package(
    name: "BeamKit",
    // Liquid Glass is the design language, not a progressive enhancement, so
    // the deployment target is the first OS that has it. Supporting one
    // release earlier would mean an `if #available` in every container view
    // and two visual languages to keep in step. See ADR-0013.
    platforms: [.iOS(.v26), .macOS(.v26)],
    products: [
        .library(name: "BeamAppShell", targets: ["BeamAppShell"])
    ],
    dependencies: [
        // Pinned exactly, not `from:`. The references this drives are pixel
        // comparisons, and the Xcode project resolves its own dependency graph
        // whose Package.resolved lives inside the generated (and gitignored)
        // .xcodeproj -- so a floating minor could change the renderer under CI
        // with nothing in the diff to explain the failure.
        .package(
            url: "https://github.com/pointfreeco/swift-snapshot-testing",
            exact: "1.19.4"
        )
    ],
    targets: [
        // Generated by `mise run core:apple`; gitignored.
        .binaryTarget(
            name: "BeamClientCoreFFI",
            path: "Frameworks/BeamClientCoreFFI.xcframework"
        ),

        // The UniFFI output, alone in its own target so it can be built in
        // Swift 5 language mode. UniFFI 0.32's async scaffolding does not
        // satisfy Swift 6's `sending` closure rules, and this is generated
        // code -- editing it would be undone by the next `core:bindgen:swift`,
        // and relaxing the mode package-wide would give up strict concurrency
        // on every line we actually wrote.
        .target(
            name: "BeamCoreBindings",
            dependencies: ["BeamClientCoreFFI"],
            path: "Sources/BeamCoreBindings",
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        .target(
            name: "BeamFFI",
            dependencies: ["BeamCoreBindings"],
            path: "Sources/BeamFFI"
        ),
        .target(name: "BeamModel", path: "Sources/BeamModel"),
        .target(
            name: "BeamCore",
            dependencies: ["BeamFFI", "BeamModel"],
            path: "Sources/BeamCore"
        ),
        .target(name: "BeamDesignSystem", path: "Sources/BeamDesignSystem"),
        .target(
            name: "BeamUI",
            dependencies: coreDependencies + ["BeamDesignSystem"],
            path: "Sources/BeamUI"
        ),
        .target(
            name: "BeamPlayback",
            dependencies: coreDependencies + ["BeamFFI"],
            path: "Sources/BeamPlayback"
        ),
        .target(
            name: "BeamTesting",
            dependencies: coreDependencies + ["BeamPlayback"],
            path: "Sources/BeamTesting"
        ),
        .target(
            name: "BeamAppShell",
            dependencies: uiDependencies + ["BeamPlayback"] + featureDependencies,
            path: "Sources/BeamAppShell"
        ),

        .testTarget(
            name: "BeamKitTests",
            dependencies: ["BeamAppShell", "BeamTesting"] + featureDependencies,
            path: "Tests/BeamKitTests"
        ),
        // Its own target so `apple:test` and `apple:snapshot` can select it:
        // the reference images are only meaningful on the one simulator they
        // were recorded on, so they must not run on every destination.
        .testTarget(
            name: "SnapshotTests",
            dependencies: [
                "BeamAppShell",
                "BeamTesting",
                .product(name: "SnapshotTesting", package: "swift-snapshot-testing"),
            ] + featureDependencies,
            path: "Tests/SnapshotTests",
            exclude: ["__Snapshots__"]
        ),
    ] + features
)
