name: Install Rust Build Dependencies
description: Installs apt packages required to build Rust crates with media/FFmpeg support

runs:
  using: composite
  steps:
    - name: Install build dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: >-
          build-essential pkg-config
          clang libclang-dev
          protobuf-compiler
          libx264-dev libx265-dev libvpx-dev
          libopus-dev libass-dev libfreetype-dev libfontconfig-dev
          libfribidi-dev libogg-dev libssl-dev
        version: 1.0
