[package]
name = "beam-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
default-run = "beam-server"

[dependencies]
beam-auth = { path = "../beam-auth", features = ["utils"] }
beam-domain = { path = "../beam-domain" }
beam-entity = { path = "../beam-entity" }
beam-index = { path = "../beam-index" }
beam-migration = { path = "../beam-migration" }
http = { workspace = true }
async-stream = "0.3"
async-trait = { workspace = true }
bytes = "1"
chrono = { workspace = true, features = ["serde"] }
color-eyre = "0.6.5"
confique = { workspace = true }
dotenvy = "0.15.7"
eyre = "0.6.12"
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
rust_decimal = "1.39.0"
salvo = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tempfile = "3.23.0"
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true, features = ["log", "release_max_level_debug"] }
tracing-subscriber = { workspace = true, features = ["json", "env-filter"] }
uuid = { workspace = true }

[dev-dependencies]
futures = "0.3.31"
beam-auth = { path = "../beam-auth", features = ["test-utils"] }
beam-domain = { path = "../beam-domain", features = ["test-utils"] }
beam-index = { path = "../beam-index", features = ["test-utils"] }
metrics-util = { workspace = true }
mockall = "0.14.0"

[features]
test-utils = ["beam-domain/test-utils", "beam-index/test-utils"]
vendored-ffmpeg = ["beam-index/vendored-ffmpeg"]
