[package]
name = "beam-server"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
publish = false
default-run = "beam-server"

[dependencies]
beam-auth = { path = "../beam-auth", features = ["utils"] }
beam-domain = { path = "../beam-domain" }
beam-entity = { path = "../beam-entity" }
beam-index = { path = "../beam-index" }
http = { workspace = true }
async-stream = "0.3"
async-trait = { workspace = true }
bytes = "1"
chrono = { workspace = true, features = ["serde"] }
color-eyre = "0.6.5"
confique = { workspace = true }
dotenvy = "0.15.7"
eyre = "0.6.12"
rand = { workspace = true }
regex = { workspace = true }
rust_decimal = "1.39.0"
salvo = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tempfile = "3.23.0"
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true, features = ["log", "release_max_level_debug"] }
tracing-subscriber = { workspace = true, features = ["json", "env-filter"] }
uuid = { workspace = true }

[dev-dependencies]
argon2 = { workspace = true }
futures = "0.3.31"
beam-auth = { path = "../beam-auth", features = ["test-utils"] }
beam-domain = { path = "../beam-domain", features = ["test-utils"] }
beam-migration = { path = "../beam-migration" }
beam-index = { path = "../beam-index", features = ["test-utils"] }
mockall = "0.14.0"

[features]
test-utils = ["beam-domain/test-utils", "beam-index/test-utils"]
vendored-ffmpeg = ["beam-index/vendored-ffmpeg"]
