[package]
name = "beam-migration"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "beam_migration"
path = "src/lib.rs"

[[bin]]
name = "beam-migration"
path = "src/main.rs"

[dependencies]
argon2 = "0.6.0"
async-trait = { workspace = true }
sea-orm-migration = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
